services:
  radarr:
    container_name: arch-radarr
    # image: radarr
    build: .
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /mnt/wd_white/downloads:/media
      - data:/var/lib/radarr
volumes:
  data:
